### PR TITLE
Add Security Policy

### PR DESCRIPTION
**Pull request by levonet**

### CODE REVIEW

**Comment by dbourdrez** [comment]
Hi @levonet,
I suggested some modifications. What do you think?

**Comment by dbourdrez** [comment]
cc @jcbbc @arthurblabla

**Comment by jcbbc** [comment]
Hi. I'm missing some context here. What is this project? Because I'm not sure it fit the Bug Bounty scope. 

More generally, we don't have any strategy on the Security Team side to support open source components so maybe we should discussed that before asking people to report issue we may not know what to do? Maybe for now, just reporting issue to the maintainers of this project (that could then ask for our help) should be enough?

**Comment by levonet** [comment]
@jcbbc
> I'm missing some context here.

This is [a collection of Github Actions](https://github.com/topics/owner-pmb2bt) that we use and decided to make public because they can be useful for the community. In our opinion, this will help make the company's brand more recognizable.

> Because I'm not sure it fit the Bug Bounty scope.

Perhaps it would be enough for us if the community reports the vulnerability, the security team will see it and pass it on to the owner team. But it seems we should be interested in case if our Github Actions will perform any unspoken actions without our knowledge. Because we use these modules in our infrastructure.

**Review by dbourdrez — APPROVED** [review]

**Comment by dbourdrez** [comment]
@jcbbc This has been reviewed, discussed, and approved with @alefauch. For now, we can leave it like this, and if we see any problem arising we are still in a position to amend it. We don't have a strong opinion and policy on open source security, yet, pending the work by @usmonster and co :)

**Comment by jcbbc** [comment]
Good to me then.

**Pull request merged**
